# -*- coding: utf-8 -*-
"""Lista1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hO3fZFwop1NxUngfiFmJtvfXN_zyYpnC
"""

# Imports

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# ---


# Carregar o Dataset

df = pd.read_csv('marketing.csv')

# df['media_cliques'] = (df['cliques'] / df['anuncios'])

df.sort_values(["cliques", "anuncios"], ascending=False)

print(f"Shape: {df.shape}\n\nColumns: {df.columns}\n\nInfo: \n{df.info}\n\nDescribe:{df.describe()}")

print(f"Value Counts:")
df.value_counts()

# Mean, Min, Max, Std, Median

print(f"Média: {df["cliques"].mean()}")
print(f"Minimo: {df["cliques"].min()}")
print(f"Maximo: {df['cliques'].max()}")
print(f"Desvio Padrão: {df['cliques'].std()}")
print(f"Mediana: {df['cliques'].median()}\n\n")

# ----------------------------------------------------------

print(f"Média: {df["anuncios"].mean()}")
print(f"Minimo: {df["anuncios"].min()}")
print(f"Maximo: {df['anuncios'].max()}")
print(f"Desvio Padrão: {df['anuncios'].std()}")
print(f"Mediana: {df['anuncios'].median()}")

"""# Gerando gráfico"""

# Gerando gráfico

plt.scatter(df['anuncios'], df['cliques'])
plt.xlabel("Anuncios")
plt.ylabel("Cliques")
plt.show()

# Verificando a correlacao entre as variaveis

df.corr()

# Histograma

df["cliques"].hist(bins=5)

# Boxplot

df.boxplot(column=["anuncios","cliques"])